version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: be-incube
        container_name: be-incube
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8081:80"
            # nanti tambahkan 443:443 kalau pakai SSL
        volumes:
            - .:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            # nanti mount juga folder certs untuk SSL
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: incube
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8082:80"
        depends_on:
            - db
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
